export const SEQUELIZE = 'SEQUELIZE';
export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';
export const PLOTS_REPOSITORY = 'PLOTS_REPOSITORY';
export const PLOTSIMAGE_REPOSITORY = 'PLOTSIMAGE_REPOSITORY';

export const PLOTSHAPE_REPOSITORY = 'PLOTSHAPE_REPOSITORY';
export const BUILDINGSHAPE_REPOSITORY = 'BUILDINGSHAPE_REPOSITORY';
export const BUILDING_REPOSITORY = 'BUILDNG_REPOSITORY';
export const BUILDINGIMAGE_REPOSITORY = 'BUILDINGIMAGE_REPOSITORY';
export const UNIT_REPOSITORY = 'UNIT_REPOSITORY';
export const HOUSEHOLD_REPOSITORY = 'HOUSEHOLD_REPOSITORY';
export const MEMBER_REPOSITORY = 'MEMBER_REPOSITORY';
